### ISSUE TITLE
mk-builder uses cross-toolchain of dead project

### ISSUE THREAD

**Issue by mhaberler** [machinekit/mk-builder#1]
@kinsamanka - I assume you are aware that http://www.emdebian.org/  is dead? 

https://github.com/machinekit/mk-builder/blob/base/mkdocker-base/Dockerfile#L14-L27

see https://wiki.debian.org/EmdebianToolchain - it is just a matter of time until this breaks?

I'd suggest replacing this with linaro cross toolchains like here: https://github.com/RobertCNelson/linux-dev/blob/master/scripts/gcc.sh

update: oh, I see - it's currently a bit of a compromise? https://wiki.debian.org/CrossToolchains#In_jessie_.28Debian_8.29

**Comment by kinsamanka** [comment]
> On 2 Apr 2016, at 11:25 AM, Michael Haberler <notifications@github.com> wrote:
> 
> @kinsamanka <https://github.com/kinsamanka> - I assume you are aware that http://www.emdebian.org/ <http://www.emdebian.org/> is dead?
> 
> https://github.com/machinekit/mk-builder/blob/base/mkdocker-base/Dockerfile#L14-L27 <https://github.com/machinekit/mk-builder/blob/base/mkdocker-base/Dockerfile#L14-L27>
> see https://wiki.debian.org/EmdebianToolchain <https://wiki.debian.org/EmdebianToolchain> - it is just a matter of time until this breaks
> 
The toolchains have moved to sid, somehow they still update the emdebian repo. ;-)

Will fix once I’m back home.

**Comment by cdsteinkuehler** [comment]
Jessie (and later) builds use multi-arch support and the Debian packaged cross compiler tool chains.  Wheezy does not have an official cross tool chain available, so the Jessie compiler is used with the native Wheezy libraries.  There are a few new CXXABI functions that do not exist in the Wheezy libraries, so if code trips up on any of these, a 'stub' function needs to be added to the "wheezy-hacks.cpp" file to avoid errors: https://github.com/machinekit/mk-builder/blob/base/bin/wheezy_hacks.cpp
